#!/bin/sh

libtoolize --automake --force --copy \
&& aclocal -I config \
&& autoheader \
&& automake --gnu --add-missing --copy \
&& autoconf

if test `basename ${0}` = "bootstrap-and-dist" ; then
        ./configure --without-mrnet --without-boost
        make dist-bzip2
fi

